include_role 'base'
# 依存元
include_cookbook 'fzf'
include_cookbook 'zsh'
include_cookbook 'git'
include_cookbook 'anyenv'
include_cookbook 'direnv'
# 開発系
include_cookbook 'emacs'
include_cookbook 'docker'
include_cookbook 'gcloud'
include_cookbook 'poetry'
include_cookbook 'gpg-agent'
include_cookbook 'ssh-agent'
# 代替系
include_cookbook 'ripgrep'
include_cookbook 'hub'
include_cookbook 'tldr'
# 便利系
include_cookbook 'gibo'
include_cookbook 'watch'
include_cookbook 'tree'
include_cookbook 'nkf'
# rust依存
# 代替系
include_cookbook 'rust'
include_cookbook 'procs'
include_cookbook 'fd'
# 便利系
include_cookbook 'tokei'
