include_role 'base'

include_cookbook 'zsh'
include_cookbook 'git'
include_cookbook 'emacs'
include_cookbook 'docker'
include_cookbook 'gcloud'
include_cookbook 'direnv'
include_cookbook 'poetry'
include_cookbook 'terraform'
